name: Profile Tetrass

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Tetrass SVGs
        uses: DaisukeKarasawa/tetrass/action@main
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            img/tetrass.svg
            img/tetrass-dark.svg?palette=github-dark

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update Tetrass SVGs"
          file_pattern: |
            img/tetrass.svg
            img/tetrass-dark.svg
